<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        let promise = new Promise(function (resolve, reject) {
            setTimeout(() => {
                let data = [1, 2, 3]
                resolve(data)
            }, 1000)
        })

        promise
            .then(
                // 这是一个异步的回调函数
                (data) => {
                    console.log('成功了', data)
                    return new Promise(function (resolve, reject) {
                        // 如果在promise的容器中直接报错了,那么直接返回一个失败的promise
                        console.log(a)
                        //   setTimeout(() => {
                        //     console.log(a)
                        //   }, 1000)
                        resolve('test')
                        // reject()
                    })
                },

                (err) => {
                    console.log('失败了', err)
                    return 1
                }
            )
            .then(
                (data) => {
                    // 链式调用之后,这个data接收的是上一次成功的回调函数的返回值
                    console.log('1成功了', data)
                    return 2
                },

                (err) => {
                    console.log('1失败了', err)
                }
            )
            .then(
                (data) => {
                    // 链式调用之后,这个data接收的是上一次成功的回调函数的返回值
                    console.log('1成功了', data)
                },

                (err) => {
                    console.log('1失败了', err)
                }
            )
    </script>
</body>

</html>